"""create_cruise_ship_table

Revision ID: 977d8e2f265b
Revises: 937d9fd4d9d2
Create Date: 2025-12-06 16:58:40.509572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977d8e2f265b'
down_revision: Union[str, None] = '937d9fd4d9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cruise_ship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('line', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('tonnage', sa.Float(), nullable=True),
    sa.Column('passengers', sa.Float(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('cabins', sa.Float(), nullable=True),
    sa.Column('passenger_density', sa.Float(), nullable=True),
    sa.Column('crew', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cruise_ship')
    # ### end Alembic commands ###